/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas_bnsp;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Nurul
 */
public class konsumen extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    private String idKonsumen;
    
    public konsumen() {
        initComponents();
        Connect();
    }public void setId(String id){
        idKonsumen= id;
    }public String getId(){
        return idKonsumen;
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bnsp","root","Prasetyo210*");
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,ex);
          
        }catch (SQLException ex) {
            
           JOptionPane.showMessageDialog(null,ex);
          
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        konsumenBaru = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        konsumenLama = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaBelakang = new javax.swing.JTextField();
        noTelp = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        namaDepan = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("FORM KONSUMEN");

        konsumenBaru.setText("Konsumen Baru");
        konsumenBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konsumenBaruActionPerformed(evt);
            }
        });

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        konsumenLama.setText("Konsumen Lama");
        konsumenLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konsumenLamaActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Depan");

        jLabel3.setText("Nama Belakang");

        jLabel4.setText("Nomor Telepon");

        id.setText("masukkan apabila pengguna lama");

        jLabel5.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kembali)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(konsumenLama)
                        .addGap(18, 18, 18)
                        .addComponent(konsumenBaru)
                        .addGap(18, 18, 18)
                        .addComponent(Reset)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(noTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaDepan, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(192, 192, 192))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaDepan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(noTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konsumenLama)
                    .addComponent(kembali)
                    .addComponent(konsumenBaru)
                    .addComponent(Reset))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void konsumenBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konsumenBaruActionPerformed
        try {
            
            pst = con.prepareStatement("insert into konsumen(nama_depan,nama_belakang, notelp) values(?,?,?)");
            
            pst.setString(1, namaDepan.getText());
            pst.setString(2, namaBelakang.getText());
            pst.setString(3, noTelp.getText());
            pst.executeUpdate();
            
            pst = con.prepareStatement("select MAX(id) from konsumen ");
            rs = pst.executeQuery();
            if(rs.next()){
                this.idKonsumen = rs.getString("MAX(id)");
            }
            
            
            
            JOptionPane.showMessageDialog(this, "Konsumen telah terdaftar");
            
            id.setText("masukkan apabila pengguna lama");
            namaDepan.setText("");
            namaBelakang.setText("");
            noTelp.setText("");
            id.requestFocus();
            
            pemesanan pesan = new pemesanan();
            pesan.setIdk(idKonsumen);
            pesan.setVisible(true);
            setVisible(false); 
            
        }catch (SQLException ex) {
            
           JOptionPane.showMessageDialog(null,ex);
          
        }
    }//GEN-LAST:event_konsumenBaruActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        makanan adm = new makanan();
        adm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void konsumenLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konsumenLamaActionPerformed
        try {
            
            pst = con.prepareStatement("select * from konsumen where id =? and nama_depan =? and nama_belakang =?");
            pst.setString(1, id.getText());
            pst.setString(2, namaDepan.getText());
            pst.setString(3, namaBelakang.getText());
            
            rs= pst.executeQuery();
            
            
            if(rs.next())
            {
               this.idKonsumen = id.getText();
               pemesanan pesan = new pemesanan();
               pesan.setIdk(idKonsumen);
               pesan.setVisible(true);
               setVisible(false); 
               System.out.println(idKonsumen);
            }
            
            else
            {
                JOptionPane.showMessageDialog(null,"Pengguna Tidak Ditemukan");
                id.setText("masukkan apabila pengguna lama");
                namaDepan.setText("");
                namaBelakang.setText("");
                noTelp.setText("");
                System.out.println(idKonsumen);
            }
            con.close();
        }catch (SQLException ex) {
            
           JOptionPane.showMessageDialog(null,ex);
          
        }
        
    }//GEN-LAST:event_konsumenLamaActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        id.setText("masukkan apabila pengguna lama");
        namaDepan.setText("");
        namaBelakang.setText("");
        noTelp.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String idKonsumen;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konsumen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    public javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton kembali;
    private javax.swing.JButton konsumenBaru;
    private javax.swing.JButton konsumenLama;
    private javax.swing.JTextField namaBelakang;
    private javax.swing.JTextField namaDepan;
    private javax.swing.JTextField noTelp;
    // End of variables declaration//GEN-END:variables
}
